[platformio]
default_envs = kc868_a32_sim

[env:kc868_a32_sim]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
  -D FAT_CONTROLLER_VERSION=\"0.2\"
  -D USE_SIM_INPUTS=1
  -D USE_KC868_IO=0
  -D HARDWARE_OUTPUTS_ARMED=0

[env:kc868_a32_hw_safe]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
  -D FAT_CONTROLLER_VERSION=\"0.2\"
  -D USE_SIM_INPUTS=0
  -D USE_KC868_IO=1
  -D HARDWARE_OUTPUTS_ARMED=0

[env:kc868_a32_hw_armed]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
  -D FAT_CONTROLLER_VERSION=\"0.2\"
  -D USE_SIM_INPUTS=0
  -D USE_KC868_IO=1
  -D HARDWARE_OUTPUTS_ARMED=1

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter =
  +<app/>
  +<hal/Kc868Mapping.cpp>
  +<sim/SimulatorCommands.cpp>
  +<sim/SimulatorLineBuffer.cpp>
